package io.sparkadvisor.analyzer.v2;

import io.sparkadvisor.core.finding.Finding;
import io.sparkadvisor.core.finding.Recommendation;
import io.sparkadvisor.core.finding.Severity;
import io.sparkadvisor.core.util.Java8Collections;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Stable catalog from docs/rules.md (30 S + 18 Q + 2 DQ). */
public final class RuleCatalogV2 {
    private RuleCatalogV2() {}

    public static List<MetricRule> all(){
        List<MetricRule> rules=new ArrayList<MetricRule>();
        addSqlRules(rules);addQueueRules(rules);addDataQualityRules(rules);
        return Java8Collections.listCopy(rules);
    }
    public static List<MetricRule> sqlAndDataQuality(){List<MetricRule> out=new ArrayList<MetricRule>();for(MetricRule r:all())if(r.scope()!=RuleScope.QUEUE)out.add(r);return Java8Collections.listCopy(out);}
    public static List<MetricRule> queue(){List<MetricRule> out=new ArrayList<MetricRule>();for(MetricRule r:all())if(r.scope()==RuleScope.QUEUE)out.add(r);return Java8Collections.listCopy(out);}

    private static void addSqlRules(List<MetricRule> r){
        r.add(new LimitInitialPartitionsRule());
        r.add(spec("S-01",RuleScope.STAGE,"skew",caps(Capability.BASE_TASK_METRICS),keys("skew.min_tasks","skew.abs_ms","skew.ratio"),(c,t)->
                c.number("num_tasks")>=t.get("skew.min_tasks")&&c.number("task_duration.max_ms")>=t.get("skew.abs_ms")&&ratio(c.number("task_duration.max_ms"),Math.max(c.number("task_duration.p50_ms"),1000))>=t.get("skew.ratio"),
                (c,t)->ratio(c.number("task_duration.max_ms"),Math.max(c.number("task_duration.p50_ms"),1000))>=10?Severity.CRITICAL:Severity.WARN,
                "Task duration is strongly skewed", recs(Recommendation.session("Tune AQE skew partition thresholds/advisory size","Long-tail tasks limit wall clock","Split skewed join partitions when applicable"),Recommendation.rewrite("Salt or pre-aggregate hot keys","Key skew is a data-shape problem","Reduce the longest task"))));
        r.add(spec("S-02",RuleScope.STAGE,"skew",caps(Capability.BASE_TASK_METRICS),keys("skew.bytes_ratio","skew.bytes_abs"),(c,t)->
                c.number("shuffle_read.max_bytes")>=t.get("skew.bytes_abs")&&ratio(c.number("shuffle_read.max_bytes"),Math.max(c.number("shuffle_read.p50_bytes"),1048576))>=t.get("skew.bytes_ratio"),Severity.WARN,"Shuffle bytes are skewed",recs(Recommendation.session("Tune AQE skew join thresholds","Byte skew predicts future long tails","Split oversized reduce partitions"),Recommendation.rewrite("Audit hot join/group keys","Distribution must be fixed at its source","Reduce partition imbalance"))));
        r.add(spec("S-03",RuleScope.STAGE,"parallelism",caps(Capability.BASE_TASK_METRICS),keys("partitions.many_tasks","partitions.tiny_ms","partitions.overhead_ratio"),(c,t)->
                c.number("num_tasks")>=t.get("partitions.many_tasks")&&c.number("task_duration.p50_ms")<=t.get("partitions.tiny_ms")&&ratio(c.number("scheduler_delay.sum_ms")+c.number("deserialize.sum_ms"),Math.max(c.number("runtime.sum_ms"),1))>=t.get("partitions.overhead_ratio"),Severity.WARN,"Too many tiny tasks",recs(Recommendation.session("Enable/tune AQE coalescing and advisoryPartitionSizeInBytes","Scheduling overhead dominates tiny tasks","Reduce task fragmentation"),Recommendation.rewrite("Remove unnecessary repartition","Hard-coded partitioning may defeat AQE","Lower fixed overhead"))));
        r.add(spec("S-04",RuleScope.STAGE,"parallelism",caps(Capability.BASE_TASK_METRICS),keys("partitions.huge_bytes"),(c,t)->
                c.number("shuffle_read.p50_bytes")>=t.get("partitions.huge_bytes")||(c.number("task_duration.p50_ms")>=600000&&c.number("num_tasks")<c.number("alive_cores")),Severity.WARN,"Partitions are too large or too few",recs(Recommendation.session("Reduce advisoryPartitionSizeInBytes or raise initialPartitionNum","Large tasks underfill the fixed core pool","Increase useful parallelism"),Recommendation.rewrite("REPARTITION on an appropriate key","Explicit repartition can correct leaf parallelism","Avoid giant tasks"))));
        r.add(spec("S-05",RuleScope.SQL,"small-files",caps(Capability.PLAN_METRICS),keys("small_files.scan_files","small_files.scan_avg_bytes"),(c,t)->
                c.number("scan.files")>=t.get("small_files.scan_files")&&ratio(c.number("scan.bytes"),Math.max(c.number("scan.files"),1))<=t.get("small_files.scan_avg_bytes"),Severity.WARN,"Scan reads many small files",recs(Recommendation.governance("Compact source files","File-open and scheduling overhead is structural","Reduce scan amplification"),Recommendation.session("Review spark.sql.files.maxPartitionBytes/openCostInBytes","Input split packing can reduce tiny tasks","Improve scan efficiency"))));
        r.add(spec("S-06",RuleScope.SQL,"small-files",caps(Capability.PLAN_METRICS),keys("small_files.out_files","small_files.out_avg_bytes"),(c,t)->
                c.number("output.files")>=t.get("small_files.out_files")&&ratio(c.number("output.bytes"),Math.max(c.number("output.files"),1))<=t.get("small_files.out_avg_bytes"),Severity.WARN,"Write produces many small files",recs(Recommendation.rewrite("REBALANCE/REPARTITION before write","Output partitioning controls file count","Produce healthier file sizes"),Recommendation.governance("Compact target table","Recurring small files require table governance","Reduce downstream scan cost"))));
        r.add(spec("S-07",RuleScope.STAGE,"memory",caps(Capability.BASE_TASK_METRICS),keys("spill.abs_bytes","spill.ratio"),(c,t)->
                c.number("spill.disk_sum_bytes")>=t.get("spill.abs_bytes")||ratio(c.number("spill.disk_sum_bytes"),Math.max(c.number("shuffle_write.sum_bytes")+c.number("input.sum_bytes"),1))>=t.get("spill.ratio"),
                (c,t)->c.number("spill.disk_sum_bytes")>=2*t.get("spill.abs_bytes")?Severity.CRITICAL:Severity.WARN,
                "Stage spills excessive data to disk",recs(Recommendation.session("Reduce per-task data with AQE/partition tuning","Spill commonly means oversized task working sets","Lower disk spill"),Recommendation.restart("Increase executor memory or reduce executor cores only after fixing partition shape","Memory per task may be insufficient","Increase safe working-set headroom"),Recommendation.rewrite("Check explode/high-cardinality aggregation","Plan shape can create oversized working sets","Remove the upstream cause"))));
        r.add(spec("S-08",RuleScope.STAGE,"memory",caps(Capability.BASE_TASK_METRICS),keys("gc.warn","gc.crit","gc.min_runtime_ms"),(c,t)->c.number("runtime.sum_ms")>=t.get("gc.min_runtime_ms")&&c.number("gc.ratio")>=t.get("gc.warn"),(c,t)->c.number("gc.ratio")>=t.get("gc.crit")?Severity.CRITICAL:Severity.WARN,"JVM GC consumes a large execution share",recs(Recommendation.restart("Review executor memory/core ratio and GC settings","Sustained GC reduces useful executor time","Reduce GC pressure"),Recommendation.session("Reduce per-task working set","Partition sizing is the safer first lever","Lower allocation pressure"))));
        r.add(spec("S-09",RuleScope.STAGE,"memory",caps(Capability.STAGE_EXECUTOR_METRICS),keys("memory.peak_risk_ratio","memory.peak_waste_ratio","memory.sizing_factor"),(c,t)->c.number("heap.peak_ratio")>=t.get("memory.peak_risk_ratio")||c.number("heap.peak_ratio")<=t.get("memory.peak_waste_ratio"),Severity.WARN,"Executor heap headroom is mis-sized",recs(Recommendation.restart("Size heap near observed peak × safety factor","Measured peak indicates risk or persistent waste","Right-size fixed executors"))));
        r.add(spec("S-10",RuleScope.STAGE,"cpu",caps(Capability.BASE_TASK_METRICS),keys("cpu.bound_ratio","cpu.io_ratio"),(c,t)->c.has("cpu.ratio"),Severity.INFO,"CPU/IO execution profile",recs(Recommendation.rewrite("Use the CPU profile to prioritize plan, UDF, compression, or layout work","The profile directs other findings; it is not a fault alone","Avoid generic tuning"))));
        r.add(spec("S-11",RuleScope.STAGE,"shuffle",caps(Capability.BASE_TASK_METRICS),keys("fetch_wait.ratio","fetch_wait.min_shuffle_bytes"),(c,t)->c.number("fetch_wait.ratio")>=t.get("fetch_wait.ratio")&&c.number("shuffle_read.sum_bytes")>=t.get("fetch_wait.min_shuffle_bytes"),Severity.WARN,"Shuffle fetch wait is high",recs(Recommendation.restart("Inspect shuffle service/network and reducer in-flight settings","Reducers spend substantial time waiting for blocks","Reduce fetch stalls"),Recommendation.rewrite("Reduce upstream shuffle and skew","Network tuning cannot fix unnecessary data movement","Lower shuffle demand"))));
        r.add(spec("S-12",RuleScope.STAGE,"serialization",caps(Capability.BASE_TASK_METRICS),keys("serialization.deser_p95_ms","serialization.result_ser_ratio","serialization.result_sum_bytes","serialization.result_task_bytes"),(c,t)->c.number("deserialize.p95_ms")>=t.get("serialization.deser_p95_ms")||c.number("result_ser.ratio")>=t.get("serialization.result_ser_ratio")||c.number("result_size.sum_bytes")>=t.get("serialization.result_sum_bytes")||c.number("result_size.max_bytes")>=t.get("serialization.result_task_bytes"),Severity.WARN,"Serialization or task result size is abnormal",recs(Recommendation.rewrite("Remove captured objects/UDF closure bloat; limit or persist large results","Large serialization and result transfer pressure the driver","Reduce driver and network risk"))));
        r.add(spec("S-23",RuleScope.STAGE,"disk",caps(Capability.BASE_TASK_METRICS),keys("shuffle_write.min_bytes","shuffle_write.throughput_bytes_per_s","shuffle_write.task_ratio"),(c,t)->(c.number("shuffle_write.sum_bytes")>=t.get("shuffle_write.min_bytes")&&c.has("shuffle_write.sum_ms")&&ratio(c.number("shuffle_write.sum_bytes"),Math.max(c.number("shuffle_write.sum_ms")/1000.0,0.001))<=t.get("shuffle_write.throughput_bytes_per_s"))||c.number("shuffle_write.max_task_ratio")>=t.get("shuffle_write.task_ratio"),Severity.WARN,"Shuffle write throughput is abnormally low",recs(Recommendation.restart("Inspect/exclude persistently slow local-disk hosts","Slow local shuffle write can indicate bad or full disks","Restore disk throughput"))));
        r.add(spec("S-24",RuleScope.STAGE,"locality",caps(Capability.BASE_TASK_METRICS),keys("locality.bad_ratio","locality.min_tasks"),(c,t)->!c.attributeIs("pure_shuffle_stage","true")&&c.number("num_tasks")>=t.get("locality.min_tasks")&&c.number("locality.bad_ratio")>=t.get("locality.bad_ratio"),Severity.WARN,"Data locality has degraded",recs(Recommendation.restart("Review spark.locality.wait and executor/data placement","ANY/RACK_LOCAL tasks amplify network traffic","Improve locality without excessive waiting"))));
        r.add(spec("S-13",RuleScope.STAGE,"scheduling",caps(Capability.BASE_TASK_METRICS),keys("scheduler_delay.p50_ms"),(c,t)->c.number("scheduler_delay.p50_ms")>=t.get("scheduler_delay.p50_ms"),Severity.WARN,"Task scheduler delay is high",recs(Recommendation.restart("Review locality wait, driver resources, and listenerbus capacity","Tasks spend too long outside useful executor work","Reduce scheduling latency"))));
        r.add(spec("S-14",RuleScope.SQL,"queue",caps(Capability.QUEUE_TIMELINE),keys("queue.wait_ratio","queue.busy_ratio"),(c,t)->c.number("queue.wait_ratio")>=t.get("queue.wait_ratio"),Severity.WARN,"SQL latency is dominated by queue/scheduling wait",recs(Recommendation.restart("Use FAIR pools, admission control, or workload isolation","Queue wait must be fixed before micro-tuning the SQL","Reduce contention latency"))));
        r.add(spec("S-15",RuleScope.SQL,"driver",caps(Capability.BASE_TASK_METRICS),keys("driver_gap.ratio","driver_gap.min_duration_ms"),(c,t)->c.number("duration_ms")>=t.get("driver_gap.min_duration_ms")&&c.number("driver_gap.ratio")>=t.get("driver_gap.ratio"),Severity.WARN,"Driver-side gaps dominate SQL latency",recs(Recommendation.governance("Reduce partition listing/metadata expansion","Driver gaps often come from listing or planning","Reduce non-task time"),Recommendation.rewrite("Simplify deeply expanded plans","Complex planning can serialize the queue","Reduce driver work"))));
        r.add(spec("S-16",RuleScope.SQL,"critical-path",caps(Capability.BASE_TASK_METRICS),keys(),(c,t)->c.has("critical_path_ms"),Severity.INFO,"Critical path decomposition",recs(Recommendation.rewrite("Prioritize stages on the critical path","Non-critical work has limited wall-clock impact","Focus tuning effort"))));
        r.add(spec("S-27",RuleScope.SQL,"driver",caps(Capability.BASE_TASK_METRICS),keys("fragmentation.min_jobs","fragmentation.job_median_ms","fragmentation.gap_ratio"),(c,t)->c.number("jobs.count")>=t.get("fragmentation.min_jobs")&&c.number("jobs.p50_ms")<=t.get("fragmentation.job_median_ms")&&c.number("driver_gap.ratio")>=t.get("fragmentation.gap_ratio"),Severity.WARN,"SQL is fragmented into many tiny jobs",recs(Recommendation.rewrite("Batch looped actions and remove per-partition submissions","Job fragmentation amplifies driver overhead","Reduce job count"),Recommendation.governance("Review partition and gateway submission design","Fragmentation may be structural","Reduce repeated launches"))));
        r.add(spec("S-17",RuleScope.SQL,"join",caps(Capability.PLAN_METRICS),keys("broadcast.opportunity_bytes"),(c,t)->(c.attributeIs("plan.has_smj","true")||c.attributeIs("plan.has_shj","true"))&&c.number("join.small_side_bytes")>0&&c.number("join.small_side_bytes")<=t.get("broadcast.opportunity_bytes"),Severity.WARN,"A measured join side may fit broadcast",recs(Recommendation.rewrite("Use BROADCAST hint after validating join legality","Measured small side can avoid shuffle","Reduce join shuffle"),Recommendation.session("Raise autoBroadcastJoinThreshold only to a measured safe bound","Global threshold changes require memory checks","Enable safe planner conversion"))));
        r.add(spec("S-18",RuleScope.SQL,"join",caps(Capability.PLAN_METRICS),keys("broadcast.risk_bytes"),(c,t)->c.number("broadcast.bytes")>=t.get("broadcast.risk_bytes")||c.attributeIs("broadcast.error","true"),Severity.CRITICAL,"Broadcast size or failure is risky",recs(Recommendation.session("Lower broadcast threshold/raise timeout only with evidence","Oversized broadcast can OOM the driver/executors","Prevent broadcast failure"),Recommendation.rewrite("Remove unsafe broadcast hint","Planner should use a scalable join","Avoid driver pressure"))));
        r.add(spec("S-19",RuleScope.SQL,"scan",caps(Capability.PLAN_TEXT),keys("small_files.prune_files"),(c,t)->c.attributeIs("plan.partition_filters_empty","true")&&c.number("scan.files")>=t.get("small_files.prune_files"),Severity.WARN,"Partition pruning may be missing",recs(Recommendation.rewrite("Add/push down partition predicates and verify DPP","Empty PartitionFilters with many files is suspicious","Reduce scanned files"))));
        r.add(spec("S-20",RuleScope.SQL,"aqe",caps(Capability.PLAN_TEXT),keys(),(c,t)->c.attributeIs("aqe.changed_plan","true")||c.number("aqe.skewed_partitions")>0||c.number("aqe.coalesced_partitions")>0,Severity.INFO,"AQE changed the runtime plan",recs(Recommendation.session("Use the final adaptive plan as the tuning baseline","AQE may already have applied the intended optimization","Avoid duplicate tuning"))));
        r.add(spec("S-25",RuleScope.SQL,"join",caps(Capability.PLAN_TEXT,Capability.PLAN_METRICS),keys("dangerous_join.bnlj_rows","dangerous_join.critical_path_ratio"),(c,t)->c.attributeIs("plan.has_cartesian","true")||(c.attributeIs("plan.has_bnlj","true")&&(c.number("join.output_rows")>=t.get("dangerous_join.bnlj_rows")||c.number("join.critical_path_ratio")>=t.get("dangerous_join.critical_path_ratio"))),Severity.CRITICAL,"Dangerous Cartesian/BNLJ operator is on a large path",recs(Recommendation.rewrite("Restore an equi-join condition or redesign range join","Cartesian/large nested-loop joins can monopolize the queue","Remove explosive join work"))));
        r.add(spec("S-26",RuleScope.SQL,"row-amplification",caps(Capability.PLAN_METRICS),keys("row_amp.ratio","row_amp.min_rows"),(c,t)->c.number("row_amp.ratio")>=t.get("row_amp.ratio")&&c.number("row_amp.output_rows")>=t.get("row_amp.min_rows"),Severity.CRITICAL,"Join/generate output rows are amplified",recs(Recommendation.rewrite("Deduplicate/pre-aggregate join keys or filter soon after explode","Row amplification is an upstream cause of spill/OOM","Reduce intermediate rows"))));
        r.add(spec("S-29",RuleScope.STAGE,"codegen",caps(Capability.PLAN_TEXT),keys("codegen.cpu_ratio","codegen.critical_path_ratio"),(c,t)->c.attributeIs("plan.codegen_gap","true")&&c.number("cpu.ratio")>=t.get("codegen.cpu_ratio")&&c.number("critical_path_ratio")>=t.get("codegen.critical_path_ratio"),Severity.WARN,"CPU-heavy critical-path operator is outside whole-stage codegen",recs(Recommendation.rewrite("Replace codegen-blocking UDFs with built-ins or split expressions","Interpreted execution wastes CPU","Restore code generation"))));
        r.add(spec("S-21",RuleScope.SQL,"reliability",caps(Capability.BASE_TASK_METRICS),keys(),(c,t)->c.number("failed_tasks")>0||c.number("stage_retries")>0,Severity.WARN,"Task failures or stage retries occurred",recs(Recommendation.restart("Classify OOM/FetchFailed/ExecutorLost/AUTH before tuning performance","Retries distort latency and may indicate platform faults","Restore reliability"))));
        r.add(spec("S-28",RuleScope.SQL,"speculation",caps(Capability.BASE_TASK_METRICS),keys("speculation.min_tasks"),(c,t)->c.number("speculative.tasks")>=t.get("speculation.min_tasks")||c.number("speculative.killed")>0,Severity.WARN,"Speculative execution has material cost",recs(Recommendation.restart("Tune speculation multiplier/quantile or repair the slow host","Losing speculative copies waste cores; winning copies may mask bad nodes","Reduce duplicate work"))));
        r.add(spec("S-22",RuleScope.SQL,"baseline",caps(Capability.BASELINE),keys("regression.ratio","regression.abs_ms","regression.min_samples","regression.baseline_rounds"),(c,t)->c.number("baseline.samples")>=t.get("regression.min_samples")&&c.number("duration.p50_ms")>=Math.max(t.get("regression.ratio")*c.number("baseline.duration.p50_ms"),c.number("baseline.duration.p50_ms")+t.get("regression.abs_ms")),(c,t)->c.attributeIs("baseline.plan_changed","true")?Severity.CRITICAL:Severity.WARN,"Fingerprint latency regressed from baseline",recs(Recommendation.governance("Trace input/shuffle growth and refresh statistics","Baseline diff identifies systemic data or stats changes","Reverse the regression"),Recommendation.rewrite("Compare old and new physical plans","Plan drift is a common silent regression","Restore the better plan"))));
    }

    private static void addQueueRules(List<MetricRule> r){
        r.add(spec("Q-01",RuleScope.QUEUE,"timeline",caps(Capability.QUEUE_TIMELINE),keys(),(c,t)->true,Severity.INFO,"Queue occupancy timeline",recs(Recommendation.governance("Review running tasks, busy ratio, failures and top consumers by time bucket","The timeline is the common evidence base for queue diagnosis","Make contention visible"))));
        r.add(spec("Q-02",RuleScope.QUEUE,"capacity",caps(Capability.QUEUE_TIMELINE),keys("capacity.idle_window_min","capacity.idle_ratio","capacity.overload_ratio"),(c,t)->c.number("idle_window_minutes")>=t.get("capacity.idle_window_min")||c.number("overload_window_minutes")>=t.get("capacity.idle_window_min"),Severity.WARN,"Queue has sustained idle or overloaded periods",recs(Recommendation.restart("Right-size or isolate capacity by time window","Fixed capacity is either wasted or saturated","Improve capacity fit"),Recommendation.governance("Shift workloads away from overload windows","Scheduling can smooth demand","Reduce queue delay"))));
        r.add(spec("Q-03",RuleScope.QUEUE,"queue",caps(Capability.QUEUE_TIMELINE),keys(),(c,t)->c.number("queue_hotspot_count")>0,Severity.WARN,"Queue wait hotspots affect multiple SQLs",recs(Recommendation.governance("Reschedule named resource hogs or apply admission control","Hotspot windows identify who blocks whom","Reduce wait loss"))));
        r.add(spec("Q-04",RuleScope.QUEUE,"fairness",caps(Capability.QUEUE_TIMELINE),keys("monopoly.window_min","monopoly.core_ratio","monopoly.min_concurrent"),(c,t)->c.number("monopoly.window_minutes")>=t.get("monopoly.window_min")&&c.number("monopoly.core_ratio")>=t.get("monopoly.core_ratio")&&c.number("monopoly.concurrent_statements")>=t.get("monopoly.min_concurrent"),Severity.CRITICAL,"One statement monopolizes the shared pool",recs(Recommendation.restart("Use FAIR pools with minShare/weight","Other active statements are starved","Improve fairness"),Recommendation.governance("Apply gateway concurrency limits","Admission control prevents a single hog","Protect tail latency"))));
        r.add(spec("Q-11",RuleScope.QUEUE,"systemic",caps(Capability.QUEUE_TIMELINE),keys("systemic.norm_median","systemic.min_concurrent"),(c,t)->c.number("systemic.norm_median")>=t.get("systemic.norm_median")&&c.number("systemic.concurrent")>=t.get("systemic.min_concurrent")&&!c.attributeIs("systemic.single_host","true"),Severity.WARN,"Multiple statements slow down systemically",recs(Recommendation.governance("Correlate the window with HDFS/network/co-located load","Cross-query slowdown points outside one SQL","Escalate platform evidence"))));
        r.add(spec("Q-05",RuleScope.QUEUE,"host",caps(Capability.HOST_METRICS),keys("host.score","host.min_tasks","host.min_stages"),(c,t)->c.number("host.max_score")>=t.get("host.score")&&c.number("host.max_samples")>=t.get("host.min_tasks")&&c.number("host.max_stages")>=t.get("host.min_stages"),Severity.WARN,"A host/executor is consistently slower",recs(Recommendation.restart("Temporarily exclude the suspect host and inspect platform metrics","Normalized task durations isolate persistent host effects","Protect the queue while repairing"))));
        r.add(spec("Q-06",RuleScope.QUEUE,"executor",caps(Capability.QUEUE_TIMELINE),keys(),(c,t)->c.number("executor.removed_count")>0,Severity.CRITICAL,"Executors were removed from a fixed pool",recs(Recommendation.restart("Classify OOM/heartbeat/removal reasons and tune only the matching cause","Executor loss amplifies retries and contention","Restore pool stability"))));
        r.add(spec("Q-07",RuleScope.QUEUE,"memory",caps(Capability.STAGE_EXECUTOR_METRICS),keys(),(c,t)->Math.abs(c.number("heap.trend_slope"))>0||c.has("heap.first_quartile_ratio"),Severity.INFO,"Executor/driver resource trend across the restart cycle",recs(Recommendation.restart("Use the measured trend to validate the daily restart interval","A rising heap/GC trend supports restart; a flat trend may not","Make restart policy evidence-based"))));
        r.add(spec("Q-08",RuleScope.QUEUE,"configuration",caps(),keys(),(c,t)->c.number("config.issue_count")>0,Severity.WARN,"Static Spark configuration has diagnosability or performance gaps",recs(Recommendation.restart("Apply the reported AQE, scheduler, event-log and safety configuration checklist","Configuration gaps affect the whole queue and next-day evidence","Improve queue defaults"))));
        r.add(spec("Q-09",RuleScope.QUEUE,"throughput",caps(Capability.QUEUE_TIMELINE),keys(),(c,t)->true,Severity.INFO,"Queue throughput and Top-N summary",recs(Recommendation.governance("Prioritize templates by frequency × median cost, not only the single slowest SQL","Aggregate cost determines queue impact","Focus work on total savings"))));
        r.add(spec("Q-10",RuleScope.QUEUE,"small-files",caps(Capability.PLAN_METRICS),keys(),(c,t)->c.number("small_files.affected_queries")>0,Severity.WARN,"Small-file findings recur across the queue",recs(Recommendation.governance("Create a table-level compaction and write-layout backlog","Repeated file issues need global governance","Reduce recurring scan/write amplification"))));
        r.add(spec("Q-12",RuleScope.QUEUE,"disk",caps(Capability.HOST_METRICS),keys("io_hotspot.host_throughput_ratio","io_hotspot.min_tasks","io_hotspot.spill_share"),(c,t)->(c.number("io.worst_host_ratio")<=t.get("io_hotspot.host_throughput_ratio")&&c.number("io.worst_host_tasks")>=t.get("io_hotspot.min_tasks"))||c.number("io.worst_host_spill_share")>=t.get("io_hotspot.spill_share"),Severity.CRITICAL,"A host has abnormal local IO throughput",recs(Recommendation.restart("Exclude and inspect the affected disk host","Cross-stage host aggregation separates bad disks from SQL symptoms","Restore local IO"))));
        r.add(spec("Q-13",RuleScope.QUEUE,"network",caps(Capability.NETWORK_MATRIX),keys("net_matrix.min_fetchfail","net_matrix.src_row_ratio","net_matrix.rack_block_ratio"),(c,t)->c.number("network.fetch_failures")>=t.get("net_matrix.min_fetchfail")&&(c.number("network.src_row_ratio")>=t.get("net_matrix.src_row_ratio")||c.number("network.rack_block_ratio")>=t.get("net_matrix.rack_block_ratio")||c.attributeIs("network.diffuse_congestion","true")),Severity.CRITICAL,"Shuffle failures/waits form a host or rack network pattern",recs(Recommendation.restart("Repair/exclude a bad source host or tune reducer in-flight limits for diffuse congestion","The src×dst pattern distinguishes host, rack and saturation causes","Reduce fetch failures"))));
        r.add(spec("Q-14",RuleScope.QUEUE,"memory",caps(Capability.QUEUE_TIMELINE),keys("oom.waterline_ratio","oom.concurrent_statements"),(c,t)->c.number("memory.pressure_events")>0,Severity.CRITICAL,"Queue-wide memory pressure needs branch-specific attribution",recs(Recommendation.rewrite("Fix the single memory-black-hole SQL when pressure is concentrated","Global heap changes would penalize the whole queue","Remove the concentrated cause"),Recommendation.restart("Raise memory/lower cores only for sustained high waterline; limit concurrency for overlap pressure","Waterline and concurrency require different remedies","Apply the correct branch"))));
        r.add(spec("Q-15",RuleScope.QUEUE,"driver",caps(Capability.QUEUE_TIMELINE),keys("driver_health.gc_ratio","driver_health.sched_delay_ms","driver_health.gap_ratio","driver_health.big_result_n"),(c,t)->c.number("driver.gc_ratio")>=t.get("driver_health.gc_ratio")||c.number("driver.scheduler_delay_p50_ms")>=t.get("driver_health.sched_delay_ms")||c.number("driver.gap_ratio_p50")>=t.get("driver_health.gap_ratio")||c.number("driver.big_result_count")>=t.get("driver_health.big_result_n"),Severity.CRITICAL,"Driver is a queue-wide bottleneck",recs(Recommendation.restart("Right-size driver and listenerbus/maxResultSize settings by the triggered dimension","The single driver serializes all queries","Protect the shared control plane"),Recommendation.governance("Reduce partition listing and result-return patterns","Some driver pressure is workload-driven","Reduce driver work"))));
        r.add(spec("Q-16",RuleScope.QUEUE,"reliability",caps(Capability.QUEUE_TIMELINE),keys("storm.fail_ratio","storm.fail_abs","storm.retry_abs"),(c,t)->(c.number("storm.failed_tasks")>=t.get("storm.fail_abs")&&c.number("storm.fail_ratio")>=t.get("storm.fail_ratio"))||c.number("storm.stage_retries")>=t.get("storm.retry_abs"),Severity.CRITICAL,"Failure/retry storm invalidates normal performance conclusions",recs(Recommendation.restart("Classify node/OOM/AUTH storm and repair renewal or executor health","Storm windows distort task metrics and require reliability-first response","Stop repeated failure waves"))));
        r.add(spec("Q-17",RuleScope.QUEUE,"restart",caps(Capability.QUEUE_TIMELINE),keys("restart_win.tail_min"),(c,t)->c.number("restart.interrupted_queries")>0||c.number("restart.tail_submissions")>0,Severity.WARN,"Restart window interrupts or endangers in-flight SQL",recs(Recommendation.governance("Drain the queue before restart and block risky tail submissions","Interrupted work wastes core-seconds and repeats next round","Make restart graceful"))));
        r.add(spec("Q-18",RuleScope.QUEUE,"baseline",caps(Capability.BASELINE),keys("queue_baseline.global_p50_ratio","queue_baseline.regressed_fraction","queue_baseline.baseline_rounds"),(c,t)->c.number("queue.duration_p50_ratio")>=t.get("queue_baseline.global_p50_ratio")||c.number("queue.regressed_fraction")>=t.get("queue_baseline.regressed_fraction"),Severity.CRITICAL,"Queue baseline drift distinguishes systemic from individual regression",recs(Recommendation.governance("Use data-volume, utilization, success and regressed-fingerprint shares to choose capacity vs SQL remediation","Many simultaneous regressions indicate a platform/data shift","Fix the correct layer"))));
    }

    private static void addDataQualityRules(List<MetricRule> r){
        r.add(spec("DQ-01",RuleScope.DATA_QUALITY,"data-quality",caps(Capability.DATA_QUALITY),keys("dq.partial_stage_warn"),(c,t)->(t.get("dq.partial_stage_warn")>0&&c.number("partial_stage_count")>0)||c.attributeIs("compacted","true")||c.attributeIs("inprogress","true")||c.number("unknown_event_count")>0,Severity.WARN,"Event log is incomplete or lossy",recs(Recommendation.restart("Increase listenerbus capacity or analyze before SHS compaction","Missing events make affected metrics lower-confidence","Restore observability"))));
        r.add(spec("DQ-02",RuleScope.DATA_QUALITY,"data-quality",caps(Capability.DATA_QUALITY),keys("dq.clock_skew_ms"),(c,t)->c.number("negative_duration_tasks")>0||Math.abs(c.number("max_clock_skew_ms"))>=t.get("dq.clock_skew_ms"),Severity.WARN,"Event timestamps are inconsistent",recs(Recommendation.governance("Correct host NTP/time synchronization","Clock skew corrupts host and occupancy attribution","Restore time consistency"))));
    }

    private interface Condition{boolean test(MetricsContext c,RuleThresholdsV2 t);}
    private interface SeverityFn{Severity severity(MetricsContext c,RuleThresholdsV2 t);}

    private static MetricRule spec(String id,RuleScope scope,String category,Set<Capability> requires,Set<String> thresholdKeys,Condition condition,Severity severity,String explanation,List<Recommendation> recs){return spec(id,scope,category,requires,thresholdKeys,condition,(c,t)->severity,explanation,recs);}
    private static MetricRule spec(final String id,final RuleScope scope,final String category,final Set<Capability> requires,final Set<String> thresholdKeys,final Condition condition,final SeverityFn severity,final String explanation,final List<Recommendation> recs){
        return new MetricRule(){
            public String id(){return id;}public RuleScope scope(){return scope;}public Set<Capability> requires(){return requires;}public Set<String> thresholdKeys(){return thresholdKeys;}
            public List<Finding> evaluate(MetricsContext c,RuleThresholdsV2 t){
                if(!condition.test(c,t))return Collections.emptyList();
                Map<String,String> evidence=new LinkedHashMap<String,String>();for(Map.Entry<String,Double> e:c.numbers().entrySet())evidence.put(e.getKey(),format(e.getValue().doubleValue()));for(Map.Entry<String,String> e:c.attributes().entrySet())evidence.put(e.getKey(),e.getValue());
                String confidence=c.partial()?"MEDIUM":"HIGH";String caveat=c.partial()?"Partial metrics: affected values may be understated.":"";
                Severity evaluated=severity.severity(c,t);Severity adjusted=c.partial()&&scope==RuleScope.STAGE&&evaluated==Severity.CRITICAL?Severity.WARN:evaluated;
                Finding f=new Finding(id,category,adjusted,c.stageId(),explanation,evidence,recs,impactScore(adjusted,c),confidence,caveat,false,"");
                return Collections.singletonList(f);
            }
        };
    }
    private static double impactScore(Severity s,MetricsContext c){double base=s==Severity.CRITICAL?100:s==Severity.WARN?10:1;double impact=Math.max(c.number("impact_core_seconds"),c.number("impact_wall_ms")/1000.0);return base*Math.log10(1+Math.max(0,impact));}
    private static double ratio(double a,double b){return b<=0?0:a/b;}
    private static String format(double value){if(value==(long)value)return Long.toString((long)value);return Double.toString(value);}
    private static Set<Capability> caps(Capability... values){EnumSet<Capability> set=EnumSet.noneOf(Capability.class);if(values!=null)Collections.addAll(set,values);return Collections.unmodifiableSet(set);}
    private static Set<String> keys(String... values){Set<String> set=new LinkedHashSet<String>();if(values!=null)Collections.addAll(set,values);return Collections.unmodifiableSet(set);}
    private static List<Recommendation> recs(Recommendation... values){List<Recommendation> out=new ArrayList<Recommendation>();if(values!=null)Collections.addAll(out,values);return Java8Collections.listCopy(out);}
}
